---
title: "Statisztika 2. szeminárium"
output: html_document
---

## 2022/2023. őszi félév
## PPKE-BTK


***

<br><br>  

## Tantárgy célja:
<br>
A tantárgy célja a Statisztika 2. előadáson tárgyalt statisztikai módszerek gyakorlása. A félév során a különböző khi-négyzet alapú próbák (függetlenség-, illeszkedés-, homogenitásvizsgálat), a korreláció, regresszió és az egyszempontú varianciaanalízis módszereit tekintjük át. Az órákon e próbák alkalmazásának feltételeivel, kiszámításuk módjával és az eredmények értelmezésével foglalkozunk.
<br><br>  

## Legfontosabb információk:
<br>
A félév során az előadáshoz kapcsolódóan végzünk számításokat számológéppel, illetve MS Excelben. A cél, hogy az egyes statisztikai módszerek matematikai hátterét megismerjék, így például tudják, hogy egy-egy SPSS művelet során mi történik, milyen adatokat veszünk alapul, és hogyan lehet a kapott eredményeket értelmezni.  
<br><br>

**Érintett témakörök:**  

1.	Kereszttábla-elemzés (és más khí-négyzet próbák): függetlenségvizsgálat, asszociációs mérőszámok, illeszkedés- és homogenitásvizsgálat
2.	Korrelációszámítás: lineáris korreláció becslése, parciális korreláció, hipotézisvizsgálatok
3.	Regressziószámítás: egyváltozós lineáris regresszió becslése, hipotézisvizsgálatok, sokváltozós lineáris regressziós modellek értelmezése
4.	Egyutas varianciaanalízis (ANOVA): kiszámítása és értelmezése, post hoc próbák

**Órai jelenlét:**  
Ahogy a korábbi félévben, nem tartom magam szigorúan a maximum három hiányzáshoz, de a korábbi félévek tapasztalatai azt mutatják, hogy az órai jelenlét növeli a siker valószínűségét. Ahhoz, hogy maximálisan profitálni tudjanak az órai jelenlétükből, érdemes a feladatokat velem együtt számolni és/vagy a kapott házi feladatokat már félév közben oldani, illetve a kérdéseiket összegyűjteni, és az órákon feltenni.  

**Házi feladatok:**  
Témakörönként egy házi feladatot fognak kapni. Ezek nem kötelezőek, de javasolt végigszámolni, hogy lássák, mi az, amit sikerült elsajátítaniuk, és mi az, amit nem. 

**Kommunikáció módja:**  
Megbeszéljük, de előreláthatólag az e-mail / MS Teams / sli.do / megosztott Google Drive mappa valamilyen kombinációja.

## Értékelés módja:  
A félév során ezúttal is két zárthelyi lesz. Hacsak nem változik a félév rendje:  

1. ZH: 2022. október 26. az 1-2. témakörből (kereszttábla + korreláció)
2. ZH: 2022. december 14. a 3-4. témakörből (regresszió + ANOVA)

A ZH-khoz minden kapott segédeszközt (képletgyűjtemény, eloszlástáblák, órai jegyzetek, házi feladatok megoldásai, stb.) használhatnak. Ezek közül képletgyűjteményt (A5 méretben) és eloszlástáblákat kapnak tőlem.  

A félév sikeres teljesítéséhez **mindkét ZH-nak legalább elégségesnek** kell lennie. Akinek nem sikerül valamelyik ZH, vagy elégedetlen a jegyével, a félév végén (várhatóan a vizsgaidőszak első hetében) javíthat.
